---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"

- name: Create Project directory
  file:
    path: "{{ home_dir }}/Projects"
    state: directory
    owner: pi
    group: pi

- name: Clone crungy repo
  git:
    repo: https://github.com/Crungeon/crungy.git
    dest: "{{ home_dir}}/Projects/crungy"
    clone: yes

- name: Set ownership over crungy
  file:
    path: "{{ home_dir }}/Projects"
    state: directory
    recurse: yes
    owner: pi
    group: pi

- name: Check if docker exists
  stat: 
    path: /usr/bin/docker
  register: docker_status

- name: 'Download docker'
  get_url:
    url: https://get.docker.com
    dest: ~/docker.sh
  when: not docker_status.stat.exists|bool
  become: yes

- name: 'Install docker'
  shell: ~/docker.sh
  when: not docker_status.stat.exists|bool
  become: yes

- name: 'Add pi to docker group'
  user:  
    name: pi
    shell: /bin/bash
    groups: docker
    append: yes

- name: 'Update APT package cache'
  action: apt update_cache=yes

- name: 'Upgrade APT to the lastest packages'
  action: apt upgrade=safe

- name: 'Install packages'
  apt:
    name: "{{ item.name }}"
    state: present
    update_cache: yes
  with_items: "{{ packages }}"

# Setup auto deploy
- name: Copy Deploy script
  copy:
    src: files/crungy-deploy.sh
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'

- name: Creates a cron job under to deploy at 1am every day.
  cron:
    name: Crungy Cron
    weekday: "0"
    minute: "0"
    hour: "1"
    user: root
    job: "/usr/local/bin/crungy-deploy.sh >> /home/pi/deploy.log"
    cron_file: crungy-cron

- name: 'Reboot'
  shell: sleep 10 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: 'Deploy Crungy'
  shell: /usr/local/bin/crungy-deploy.sh >> /home/pi/init-deploy.log

- name: "Wait for Raspberry PI to come back"
  local_action: wait_for host={{ real_ansible_host }} port=22 state=started delay=10
  become: false
